import type { ProxyModel, TaskTemplate, TemplateRun } from "../flows/model";

/** The models CLIProxyAPI listed on 2026-09-28, by the ProxyCli provider that serves them. */
export const proxyModels: ProxyModel[] = [
    { id: "codex-auto-review", provider: "codex" },
    { id: "gpt-5.5", provider: "codex" },
    { id: "gpt-5.6-luna", provider: "codex" },
    { id: "gpt-5.6-sol", provider: "codex" },
    { id: "gpt-5.6-terra", provider: "codex" },
    { id: "gpt-6-astra", provider: "codex" },
    { id: "gpt-6-luna", provider: "codex" },
    { id: "gpt-6-sol", provider: "codex" },
    { id: "gemini-3.7-flash-high", provider: "antigravity" },
    { id: "gemini-3.8-flash-high", provider: "antigravity" },
    { id: "grok-4.6", provider: "grok" },
    { id: "grok-4.7", provider: "grok" },
    { id: "grok-4.7-build-fast", provider: "grok" },
    { id: "grok-composer-2.5-fast", provider: "grok" },
    { id: "kimi-k2.6", provider: "kimi" },
    { id: "kimi-k2.7-code", provider: "kimi" },
    { id: "kimi-k2.7-code-highspeed", provider: "kimi" },
    { id: "kimi-k2.8", provider: "kimi" },
    { id: "kimi-k2.8-code", provider: "kimi" },
    { id: "kimi-k3", provider: "kimi" },
];

/** Hand-written templates and runs for the flow viewer, until the Gateway serves them. */
export const templates: TaskTemplate[] = [
    {
        name: "maintenance",
        title: "Weekly maintenance",
        project_slug: "orbit-website",
        status: "todo",
        cron: "0 3 * * 1",
        app: "orbit-website",
        tasks: [
            {
                key: "update",
                title: "Update dependencies",
                kind: "agent",
                implementer_model: "gpt-5.6-luna",
                reviewer_model: "gpt-6-sol",
                brief: "Update the Composer and npm dependencies, and fix what the update breaks.",
                stats: {
                    runs: 12,
                    outcomes: { passed: 9, skipped: 3 },
                    avg_duration_ms: 14 * 60_000,
                    avg_tokens: 182_000,
                },
            },
            {
                key: "size",
                title: "Major upgrade?",
                kind: "decide",
                question: "Does this update contain a major version upgrade?",
                options: ["major", "minor"],
                evidence: ["update"],
                min_probability: 0.8,
                routes: { major: "review", minor: "browser" },
                stats: {
                    runs: 9,
                    outcomes: { major: 2, minor: 7 },
                    avg_duration_ms: 2_000,
                    avg_tokens: 1_400,
                },
            },
            {
                key: "review",
                title: "Adapt to major upgrades",
                kind: "agent",
                implementer_model: "gpt-6-luna",
                reviewer_model: "gpt-6-sol",
                brief: "Read the changelogs of the major upgrades and adapt the App.",
                stats: {
                    runs: 2,
                    outcomes: { passed: 2 },
                    avg_duration_ms: 31 * 60_000,
                    avg_tokens: 420_000,
                },
            },
            {
                key: "browser",
                title: "Browser tests",
                kind: "check",
                commands: ["bunx playwright test --project=e2e"],
                stats: {
                    runs: 9,
                    outcomes: { passed: 8, failed: 1 },
                    avg_duration_ms: 3 * 60_000,
                    avg_tokens: null,
                },
            },
            {
                key: "merge",
                title: "Merge the pull request",
                kind: "merge",
                stats: {
                    runs: 8,
                    outcomes: { passed: 8 },
                    avg_duration_ms: 6 * 60_000,
                    avg_tokens: null,
                },
            },
            {
                key: "deploy",
                title: "Deploy production",
                kind: "action",
                operation: "instance:deploy",
                arguments: { instance: 4 },
                stats: {
                    runs: 8,
                    outcomes: { passed: 8 },
                    avg_duration_ms: 90_000,
                    avg_tokens: null,
                },
            },
            {
                key: "verify",
                title: "Smoke test production",
                kind: "check",
                commands: ["bunx playwright test --project=smoke --base-url=https://orbit.nckrtl.com"],
                routes: { passed: "complete", failed: "rollback" },
                stats: {
                    runs: 8,
                    outcomes: { passed: 7, failed: 1 },
                    avg_duration_ms: 40_000,
                    avg_tokens: null,
                },
            },
            {
                key: "rollback",
                title: "Roll back production",
                kind: "action",
                operation: "instance:rollback",
                arguments: { instance: 4 },
                routes: { passed: "fail" },
                stats: {
                    runs: 1,
                    outcomes: { passed: 1 },
                    avg_duration_ms: 20_000,
                    avg_tokens: null,
                },
            },
        ],
    },
    {
        name: "today",
        title: "Orbit task flow (today)",
        project_slug: "orbit",
        status: "backlog",
        cron: null,
        app: null,
        phases: [
            {
                key: "prepare",
                title: "Prepare",
                brief: "You and the ADE agree the behavior, write the contract, and split the work. Nothing runs yet.",
            },
            {
                key: "start",
                title: "Start the workspace",
                brief: "The Gateway claims the group, provisions its task-{group id} workspace, and runs the baseline check once.",
            },
            {
                key: "task",
                title: "Each Task",
                brief: "One Task at a time, in position order: implement, check, review, publish. Every Task gets a fresh implementer and a fresh reviewer.",
                repeat: "once per Task, in order",
            },
            {
                key: "settle",
                title: "Pull request",
                brief: "The Gateway opens the pull request and watches it. A conflict or a failed check gets a fixup Task.",
            },
            {
                key: "review",
                title: "Review and merge",
                brief: "People check the whole feature on Incus and merge it. The Gateway never merges.",
            },
        ],
        tasks: [
            {
                key: "contract",
                phase: "prepare",
                title: "Write the contract",
                kind: "human",
                actor: "you + ADE · grill-with-docs",
                brief: "Agree the behavior, then commit the ADRs and documentation to branch task-{group id} and push it. The engine treats the branch as optional; Orbit's policy requires it. Tasks: Prepare a group in Backlog; contributor guide §1–2.",
            },
            {
                key: "create",
                phase: "prepare",
                title: "Create the group and its Tasks",
                kind: "human",
                actor: "ADE · tasks:create",
                brief: "The group starts in backlog, without a workspace. Task 1 writes the documentation, with the bin/docs-impact report. Each Task has one goal and at most five typed deliverables. The last Task absorbs the ADRs. Skill orbit-tasks.",
            },
            {
                key: "approve",
                phase: "prepare",
                title: "Approve and move to Todo",
                kind: "human",
                actor: "you · tasks:update",
                brief: "You review the numbered breakdown. Moving to todo needs at least one deliverable on every Task. Skill orbit-tasks: Review the breakdown.",
            },
            {
                key: "claim",
                phase: "start",
                title: "Claim and provision",
                kind: "action",
                actor: "Gateway · tasks:tick every 10 s",
                brief: "The tick claims the oldest todo group that fits: an app-dev Node with fewer than 10 active groups whose t3-code and pi-server Processes run. The fewest-loaded Node wins. A failed claim returns the group to todo with a reason, and a later tick retries. Tasks: Scheduler, Claim and provision.",
            },
            {
                key: "baseline",
                phase: "start",
                title: "Baseline check",
                kind: "check",
                actor: "Project task check · composer check",
                commands: ["setup steps", "dependency install", "composer check"],
                brief: "Before the first implementer, the check runs the Project setup steps, installs dependencies, and runs composer check on the fresh workspace. A failure asks for assistance at once; fix the cause, then cancel and create the group again. Tasks: Baseline check.",
                routes: { failed: "fail" },
            },
            {
                key: "implement",
                phase: "task",
                title: "Implementer turn",
                kind: "agent",
                implementer_model: "grok-4.7",
                actor: "Pi · CLIProxyAPI",
                options: ["ready for review"],
                routes: { "ready for review": "handoff" },
                brief: "A fresh implementer thread on Pi (grok-4.7 through CLIProxyAPI, effort high) works the Task and ends with .git/orbit/run --outcome=ready_for_review, confirming each deliverable. blocked asks you one question and pauses the group; your resolution continues the same thread. Tasks: Agent threads, Run receipt.",
            },
            {
                key: "handoff",
                phase: "task",
                title: "Handoff check",
                kind: "check",
                actor: "Gateway rubric + task check",
                commands: ["rubric: receipt, no pending input, check script", "composer check (bin/review-check)", "verify deliverables"],
                brief: "The rubric checks the receipt in code. Then the Gateway runs composer check on the whole working tree and verifies the typed deliverables. A failure sends one reminder with the output; a second failure asks for assistance. Tasks: Rubric and reminders, Project check.",
                options: ["passed", "failed"],
                routes: { passed: "review", failed: "implement" },
            },
            {
                key: "review",
                phase: "task",
                title: "Reviewer turn",
                kind: "agent",
                reviewer_model: "claude-opus-5-5",
                actor: "T3 · claudeAgent",
                brief: "A fresh, read-only reviewer thread per Task on T3 (claude-opus-5-5, effort high) reads a review packet of at most 16,000 characters and ends with approved, changes_requested, or blocked. It does not rerun the checks. A re-review continues the same thread. Tasks: Review a subtask.",
                options: ["approved", "changes requested"],
                routes: { approved: "coverage", "changes requested": "implement" },
            },
            {
                key: "coverage",
                phase: "task",
                title: "Brief coverage (last Task only)",
                kind: "decide",
                question: "Does a listed pull request change deliver this Task?",
                options: ["covered", "missing"],
                evidence: ["review"],
                min_probability: 0.5,
                brief: "Only before the commit of the Task that opens the pull request: Jev (jev-latest on TypeSafe) checks that the reviewer's change list covers every delivered Task. A missing Task fails brief_coverage, and the reviewer's reminder names it. Other Tasks skip this step. Tasks: Pull request and settle metrics.",
                routes: { covered: "publish", missing: "review" },
            },
            {
                key: "publish",
                phase: "task",
                title: "Commit and push",
                kind: "action",
                actor: "Gateway · GitHub App",
                brief: "The Gateway commits the whole workspace as orbit <tasks@orbit> and pushes that commit to task-{group id}, never forced. A failed push retries after 1, 2, 5, 10, and 30 minutes; the fifth failure asks for assistance. Tasks: Pull request and settle metrics.",
            },
            {
                key: "next",
                phase: "task",
                title: "Next Task?",
                kind: "check",
                actor: "Gateway",
                brief: "The next todo Task starts only after every earlier Task has ended. After the last Task, the Gateway opens the pull request.",
                options: ["last Task", "next Task"],
                routes: { "last Task": "open-pr", "next Task": "implement" },
            },
            {
                key: "open-pr",
                phase: "settle",
                title: "Open the pull request",
                kind: "action",
                actor: "Gateway · GitHub App",
                brief: "The Gateway opens the pull request against the default branch with the reviewer's summary, changes, and breaking changes, stores pr_url, and moves the group to settling. Tasks: Pull request and settle metrics.",
            },
            {
                key: "watch",
                phase: "settle",
                title: "Watch the pull request",
                kind: "check",
                actor: "Gateway · GitHub App, each tick",
                brief: "Each tick reads the pull request. A conflict or a genuine check failure gets a fixup. Cancelled checks, checks that could not start, and checks pending over 60 minutes are infrastructure: the group waits on a backoff, then asks for assistance. Tasks: Settling, Fix a settling pull request.",
                options: ["healthy", "conflict or failed check"],
                routes: { healthy: "incus", "conflict or failed check": "fixup" },
            },
            {
                key: "fixup",
                phase: "settle",
                title: "Append a fixup Task",
                kind: "action",
                actor: "Gateway",
                brief: "The Gateway appends 'Merge origin/main' or 'Fix {check}' with a composer check deliverable and returns the group to running. It runs as a normal Task and pushes to the same pull request. At most two fixups per problem and three per group, until a person adds a Task. Tasks: Fix a settling pull request.",
                options: ["appended"],
                routes: { appended: "implement" },
            },
            {
                key: "incus",
                phase: "review",
                title: "Independent code and Incus review",
                kind: "human",
                actor: "independent reviewer · reviewing-pull-requests",
                brief: "The reviewer checks the code, documentation, and ADRs, and reproduces the feature on an Incus topology. It records the revision, environment, acceptance, CI, limitations, and verdict. Findings come back as a new Task. Feature delivery: Review on Incus.",
                options: ["ready", "findings"],
                routes: { ready: "merge", findings: "implement" },
            },
            {
                key: "merge",
                phase: "review",
                title: "Approve and merge",
                kind: "human",
                actor: "you · merging-pull-requests",
                brief: "A merge needs passing CI, a successful independent review, resolved findings, and your approval. GitHub enforces none of these; the person who merges applies them. A pull request closed without merging asks for assistance. Feature delivery: Merge and cleanup.",
                options: ["merged", "closed without merge"],
                routes: { merged: "cleanup", "closed without merge": "fail" },
            },
            {
                key: "cleanup",
                title: "Complete and remove the workspace",
                kind: "action",
                actor: "Gateway · next tick",
                brief: "The next tick sees the merge, completes the group, removes the workspace and its Incus bridge worktree, and archives the T3 threads. A failed removal asks for assistance, and the sweep retries. Tasks: Complete and cleanup.",
                routes: { passed: "complete" },
            },
        ],
    },
    {
        name: "feature",
        title: "Orbit feature",
        project_slug: "orbit",
        status: "backlog",
        cron: null,
        app: null,
        tasks: [
            {
                key: "docs",
                title: "ADRs and documentation",
                kind: "agent",
                implementer_model: "gpt-6-sol",
                reviewer_model: "claude-opus-5",
                brief: "Write the ADR and update the documentation that the feature changes.",
            },
            {
                key: "implement",
                title: "Implementation",
                kind: "agent",
                implementer_model: "gpt-5.6-luna",
                reviewer_model: "claude-opus-5",
                brief: "Build the behavior the documentation describes.",
            },
            { key: "merge", title: "Merge the pull request", kind: "merge" },
        ],
    },
    {
        name: "content",
        title: "Website article",
        project_slug: "orbit-website",
        status: "backlog",
        cron: null,
        app: "orbit-website",
        tasks: [
            {
                key: "draft",
                title: "Draft the article",
                kind: "agent",
                implementer_model: "kimi-k2.8",
                reviewer_model: "gpt-5.6-sol",
                brief: "Write the article in the website repository from the brief.",
            },
            {
                key: "lint",
                title: "Prose and link checks",
                kind: "check",
                commands: ["bun run content:lint"],
            },
            { key: "merge", title: "Merge the pull request", kind: "merge" },
            {
                key: "deploy",
                title: "Deploy production",
                kind: "action",
                operation: "instance:deploy",
                arguments: { instance: 4 },
            },
        ],
    },
];

const minutes = (count: number) => count * 60_000;

export const runs: TemplateRun[] = [
    {
        id: 412,
        template: "orbit-website/maintenance",
        title: "Weekly maintenance · 28 Sep",
        status: "running",
        started_at: "2026-09-28T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "passed", duration_ms: minutes(12), tokens: 164_000, implementer_model: "gpt-5.6-luna", reviewer_model: "gpt-6-sol" },
            {
                key: "size",
                status: "completed",
                outcome: "minor",
                duration_ms: 1_800,
                tokens: 1_300,
                probabilities: { minor: 0.94, major: 0.06 },
            },
            { key: "review", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "browser", status: "running", outcome: null, duration_ms: null, tokens: null },
            { key: "merge", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "deploy", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "verify", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "rollback", status: "todo", outcome: null, duration_ms: null, tokens: null },
        ],
    },
    {
        id: 398,
        template: "orbit-website/maintenance",
        title: "Weekly maintenance · 21 Sep",
        status: "failed",
        started_at: "2026-09-21T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "passed", duration_ms: minutes(16), tokens: 201_000, implementer_model: "gpt-5.6-luna", reviewer_model: "gpt-6-sol" },
            {
                key: "size",
                status: "completed",
                outcome: "major",
                duration_ms: 2_100,
                tokens: 1_500,
                probabilities: { major: 0.88, minor: 0.12 },
            },
            { key: "review", status: "completed", outcome: "passed", duration_ms: minutes(34), tokens: 452_000, implementer_model: "gpt-6-luna", reviewer_model: "gpt-6-sol" },
            { key: "browser", status: "completed", outcome: "passed", duration_ms: minutes(3), tokens: null },
            { key: "merge", status: "completed", outcome: "passed", duration_ms: minutes(7), tokens: null },
            { key: "deploy", status: "completed", outcome: "passed", duration_ms: 95_000, tokens: null },
            { key: "verify", status: "failed", outcome: "failed", duration_ms: 38_000, tokens: null },
            { key: "rollback", status: "completed", outcome: "passed", duration_ms: 21_000, tokens: null },
        ],
    },
    {
        id: 377,
        template: "orbit-website/maintenance",
        title: "Weekly maintenance · 14 Sep",
        status: "completed",
        started_at: "2026-09-14T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "skipped", duration_ms: minutes(4), tokens: 38_000, implementer_model: "gpt-5.6-luna", reviewer_model: "gpt-6-sol" },
            { key: "size", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "review", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "browser", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "merge", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "deploy", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "verify", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "rollback", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
        ],
    },
];
