import type { ProxyModel, TaskTemplate, TemplateRun } from "../flows/model";

/** The models CLIProxyAPI listed on 2026-09-28, by the ProxyCli provider that serves them. */
export const proxyModels: ProxyModel[] = [
    { id: "codex-auto-review", provider: "codex" },
    { id: "gpt-5.5", provider: "codex" },
    { id: "gpt-5.6-luna", provider: "codex" },
    { id: "gpt-5.6-sol", provider: "codex" },
    { id: "gpt-5.6-terra", provider: "codex" },
    { id: "gpt-6-astra", provider: "codex" },
    { id: "gpt-6-luna", provider: "codex" },
    { id: "gpt-6-sol", provider: "codex" },
    { id: "gemini-3.7-flash-high", provider: "antigravity" },
    { id: "gemini-3.8-flash-high", provider: "antigravity" },
    { id: "grok-4.6", provider: "grok" },
    { id: "grok-4.7", provider: "grok" },
    { id: "grok-4.7-build-fast", provider: "grok" },
    { id: "grok-composer-2.5-fast", provider: "grok" },
    { id: "kimi-k2.6", provider: "kimi" },
    { id: "kimi-k2.7-code", provider: "kimi" },
    { id: "kimi-k2.7-code-highspeed", provider: "kimi" },
    { id: "kimi-k2.8", provider: "kimi" },
    { id: "kimi-k2.8-code", provider: "kimi" },
    { id: "kimi-k3", provider: "kimi" },
];

/** Hand-written templates and runs for the flow viewer, until the Gateway serves them. */
export const templates: TaskTemplate[] = [
    {
        name: "maintenance",
        title: "Weekly maintenance",
        project_slug: "orbit-website",
        status: "todo",
        cron: "0 3 * * 1",
        app: "orbit-website",
        tasks: [
            {
                key: "update",
                title: "Update dependencies",
                kind: "agent",
                implementer_model: "gpt-5.6-luna",
                reviewer_model: "gpt-6-sol",
                brief: "Update the Composer and npm dependencies, and fix what the update breaks.",
                stats: {
                    runs: 12,
                    outcomes: { passed: 9, skipped: 3 },
                    avg_duration_ms: 14 * 60_000,
                    avg_tokens: 182_000,
                },
            },
            {
                key: "size",
                title: "Major upgrade?",
                kind: "decide",
                question: "Does this update contain a major version upgrade?",
                options: ["major", "minor"],
                evidence: ["update"],
                min_probability: 0.8,
                routes: { major: "review", minor: "browser" },
                stats: {
                    runs: 9,
                    outcomes: { major: 2, minor: 7 },
                    avg_duration_ms: 2_000,
                    avg_tokens: 1_400,
                },
            },
            {
                key: "review",
                title: "Adapt to major upgrades",
                kind: "agent",
                implementer_model: "gpt-6-luna",
                reviewer_model: "gpt-6-sol",
                brief: "Read the changelogs of the major upgrades and adapt the App.",
                stats: {
                    runs: 2,
                    outcomes: { passed: 2 },
                    avg_duration_ms: 31 * 60_000,
                    avg_tokens: 420_000,
                },
            },
            {
                key: "browser",
                title: "Browser tests",
                kind: "check",
                commands: ["bunx playwright test --project=e2e"],
                stats: {
                    runs: 9,
                    outcomes: { passed: 8, failed: 1 },
                    avg_duration_ms: 3 * 60_000,
                    avg_tokens: null,
                },
            },
            {
                key: "merge",
                title: "Merge the pull request",
                kind: "merge",
                stats: {
                    runs: 8,
                    outcomes: { passed: 8 },
                    avg_duration_ms: 6 * 60_000,
                    avg_tokens: null,
                },
            },
            {
                key: "deploy",
                title: "Deploy production",
                kind: "action",
                operation: "instance:deploy",
                arguments: { instance: 4 },
                stats: {
                    runs: 8,
                    outcomes: { passed: 8 },
                    avg_duration_ms: 90_000,
                    avg_tokens: null,
                },
            },
            {
                key: "verify",
                title: "Smoke test production",
                kind: "check",
                commands: ["bunx playwright test --project=smoke --base-url=https://orbit.nckrtl.com"],
                routes: { passed: "complete", failed: "rollback" },
                stats: {
                    runs: 8,
                    outcomes: { passed: 7, failed: 1 },
                    avg_duration_ms: 40_000,
                    avg_tokens: null,
                },
            },
            {
                key: "rollback",
                title: "Roll back production",
                kind: "action",
                operation: "instance:rollback",
                arguments: { instance: 4 },
                routes: { passed: "fail" },
                stats: {
                    runs: 1,
                    outcomes: { passed: 1 },
                    avg_duration_ms: 20_000,
                    avg_tokens: null,
                },
            },
        ],
    },
    {
        name: "today",
        title: "Orbit task flow (today)",
        project_slug: "orbit",
        status: "backlog",
        cron: null,
        app: null,
        tasks: [
            {
                key: "shape",
                title: "Shape the feature",
                kind: "human",
                actor: "operator + ADE · grill-with-docs",
                brief: "Agree the behavior, then write the ADRs and documentation on branch task-{group id} and push it. Contributor guide §1–2; skills grill-with-docs and orbit-tasks.",
            },
            {
                key: "create",
                title: "Create the group in Backlog",
                kind: "human",
                actor: "ADE · tasks:create",
                brief: "Create the group and its ordered subtasks with typed deliverables, at most five each. Subtask 1 is always docs, with the bin/docs-impact report. The last subtask absorbs the ADRs. Tasks reference: Prepare a group in Backlog; orbit-tasks skill.",
            },
            {
                key: "approve",
                title: "Approve the breakdown, move to Todo",
                kind: "human",
                actor: "operator · tasks:update",
                brief: "The operator reviews the numbered breakdown and moves the group to todo. Every subtask needs at least one deliverable, or the move is refused. orbit-tasks: Review the breakdown.",
            },
            {
                key: "claim",
                title: "Claim and provision the workspace",
                kind: "action",
                actor: "Gateway scheduler · tasks:tick",
                brief: "The tick claims the oldest todo group that fits the Node ceiling of 10 active groups, marks it reserved, and provisions Instance task-{group id} on an app-dev Node with T3 or Pi. A failed provision returns the group to todo with an assistance reason, and a later tick tries again. Tasks reference: Scheduler and ceilings, Shared Instance.",
            },
            {
                key: "baseline",
                title: "Baseline check",
                kind: "check",
                actor: "Project task check · composer check",
                commands: ["Project setup steps", "composer check (bin/review-check)"],
                brief: "Before the first implementer, Orbit runs the Project setup steps, prepares dependencies, and runs the task check on the fresh workspace. A failure asks for assistance: fix the cause, then cancel and create the group again. Tasks reference: Project check.",
                routes: { failed: "fail" },
            },
            {
                key: "implement",
                title: "Implementer turn",
                kind: "agent",
                implementer_model: "gpt-5.6-luna",
                brief: "A fresh implementer thread on T3 (codex, effort high) works the subtask and ends with .git/orbit/run --outcome=ready_for_review, confirming each deliverable. `blocked` asks the operator one question; the answer continues the same thread. One subtask runs at a time, in position order. Tasks reference: T3 driver.",
            },
            {
                key: "handoff",
                title: "Handoff checks",
                kind: "check",
                actor: "Gateway rubric + task check",
                commands: ["run receipt, composer check script, no pending input", "composer check (bin/review-check, docs impact)", "verify deliverables"],
                brief: "The rubric checks the receipt without a model. Then Orbit runs the task check on the whole working tree and verifies the typed deliverables. A failure sends the implementer one reminder with the output; a second failure asks for assistance. Tasks reference: Session routing, Project check, Verify deliverables.",
                options: ["passed", "failed"],
                routes: { passed: "review", failed: "implement" },
            },
            {
                key: "review",
                title: "Reviewer turn",
                kind: "agent",
                reviewer_model: "claude-opus-5",
                brief: "A fresh, read-only reviewer thread per subtask (T3 claudeAgent, effort high) reads the review packet and ends with approved, changes_requested, or blocked. Changes are relayed to the implementer, and the re-review continues this thread. A reviewer that edits the workspace gets a reminder. Tasks reference: Review a subtask.",
                options: ["approved", "changes requested"],
                routes: { approved: "coverage", "changes requested": "implement" },
            },
            {
                key: "coverage",
                title: "Brief coverage (last subtask only)",
                kind: "decide",
                question: "Does a listed pull request change deliver this subtask?",
                options: ["covered", "missing"],
                evidence: ["review"],
                min_probability: 0.5,
                brief: "Only before the last subtask's commit: Jev checks that the reviewer's pull request change list covers every delivered subtask. A missing subtask fails brief_coverage, and the reviewer's reminder names it. Earlier subtasks skip this step. Tasks reference: Pull request and settle metrics.",
                routes: { covered: "commit", missing: "review" },
            },
            {
                key: "commit",
                title: "Commit and push the approval",
                kind: "action",
                actor: "Gateway · GitHub App",
                brief: "Orbit commits the whole workspace as orbit <tasks@orbit> and pushes that stored commit to task-{group id}. A failed push retries after 1, 2, 5, 10, and 30 minutes, and the fifth failure asks for assistance. Tasks reference: Pull request and settle metrics.",
            },
            {
                key: "more",
                title: "More subtasks?",
                kind: "check",
                actor: "Gateway scheduler",
                brief: "The next todo subtask starts with a fresh implementer. After the last approval, Orbit opens the pull request.",
                options: ["last subtask", "next subtask"],
                routes: { "last subtask": "open-pr", "next subtask": "implement" },
            },
            {
                key: "open-pr",
                title: "Open the pull request",
                kind: "action",
                actor: "Gateway · GitHub App",
                brief: "Orbit opens the pull request against the default branch with the reviewer's summary, changes, and breaking changes, stores pr_url, and moves the group to settling. A failed open uses the push backoff. Tasks reference: Pull request and settle metrics.",
            },
            {
                key: "ci",
                title: "Watch CI and conflicts",
                kind: "check",
                actor: "Gateway · GitHub App, each tick",
                brief: "While settling, each tick reads the pull request. A conflict or a genuine check failure gets a fixup. Cancelled checks, checks that could not start, and checks pending over 60 minutes are infrastructure: the group waits on the backoff, then asks for assistance. Tasks reference: Fix a settling pull request.",
                options: ["green", "conflict or failed check"],
                routes: { green: "incus", "conflict or failed check": "fixup" },
            },
            {
                key: "fixup",
                title: "Append a fixup subtask",
                kind: "action",
                actor: "Gateway",
                brief: "Orbit appends 'Merge origin/main' or 'Fix {check}' with a composer check deliverable and returns the group to running. It runs the full subtask cycle with new threads and pushes to the same pull request. Caps: two fixups per problem and three per group, until a person adds a subtask. Tasks reference: Fix a settling pull request.",
                options: ["appended"],
                routes: { appended: "implement" },
            },
            {
                key: "incus",
                title: "Independent code and Incus review",
                kind: "human",
                actor: "independent reviewer · reviewing-pull-requests",
                brief: "Orbit's independent reviewer checks the code, documentation, and ADRs and reproduces the feature on an Incus topology, recording the commit, environment, actions, results, and limits. Findings go back as a new subtask. Contributor guide: Review and merge.",
                options: ["approved", "findings"],
                routes: { approved: "merge", findings: "implement" },
            },
            {
                key: "merge",
                title: "Maintainer approval and merge",
                kind: "human",
                actor: "maintainer · merging-pull-requests",
                brief: "A merge needs passing CI, a successful independent review, resolved findings, and the maintainer's approval. The Gateway does not merge. A pull request closed without merging asks for assistance. Contributor guide: Review and merge.",
                options: ["merged", "closed without merge"],
                routes: { merged: "cleanup", "closed without merge": "fail" },
            },
            {
                key: "cleanup",
                title: "Complete and remove the workspace",
                kind: "action",
                actor: "Gateway",
                brief: "Settling sees the merge, completes the group, removes the Instance and its checkout, and archives the T3 threads. A failed removal asks for assistance and the sweep retries on the backoff. Tasks reference: Complete and cleanup.",
                routes: { passed: "complete" },
            },
        ],
    },
    {
        name: "feature",
        title: "Orbit feature",
        project_slug: "orbit",
        status: "backlog",
        cron: null,
        app: null,
        tasks: [
            {
                key: "docs",
                title: "ADRs and documentation",
                kind: "agent",
                implementer_model: "gpt-6-sol",
                reviewer_model: "claude-opus-5",
                brief: "Write the ADR and update the documentation that the feature changes.",
            },
            {
                key: "implement",
                title: "Implementation",
                kind: "agent",
                implementer_model: "gpt-5.6-luna",
                reviewer_model: "claude-opus-5",
                brief: "Build the behavior the documentation describes.",
            },
            { key: "merge", title: "Merge the pull request", kind: "merge" },
        ],
    },
    {
        name: "content",
        title: "Website article",
        project_slug: "orbit-website",
        status: "backlog",
        cron: null,
        app: "orbit-website",
        tasks: [
            {
                key: "draft",
                title: "Draft the article",
                kind: "agent",
                implementer_model: "kimi-k2.8",
                reviewer_model: "gpt-5.6-sol",
                brief: "Write the article in the website repository from the brief.",
            },
            {
                key: "lint",
                title: "Prose and link checks",
                kind: "check",
                commands: ["bun run content:lint"],
            },
            { key: "merge", title: "Merge the pull request", kind: "merge" },
            {
                key: "deploy",
                title: "Deploy production",
                kind: "action",
                operation: "instance:deploy",
                arguments: { instance: 4 },
            },
        ],
    },
];

const minutes = (count: number) => count * 60_000;

export const runs: TemplateRun[] = [
    {
        id: 412,
        template: "orbit-website/maintenance",
        title: "Weekly maintenance · 28 Sep",
        status: "running",
        started_at: "2026-09-28T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "passed", duration_ms: minutes(12), tokens: 164_000, implementer_model: "gpt-5.6-luna", reviewer_model: "gpt-6-sol" },
            {
                key: "size",
                status: "completed",
                outcome: "minor",
                duration_ms: 1_800,
                tokens: 1_300,
                probabilities: { minor: 0.94, major: 0.06 },
            },
            { key: "review", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "browser", status: "running", outcome: null, duration_ms: null, tokens: null },
            { key: "merge", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "deploy", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "verify", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "rollback", status: "todo", outcome: null, duration_ms: null, tokens: null },
        ],
    },
    {
        id: 398,
        template: "orbit-website/maintenance",
        title: "Weekly maintenance · 21 Sep",
        status: "failed",
        started_at: "2026-09-21T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "passed", duration_ms: minutes(16), tokens: 201_000, implementer_model: "gpt-5.6-luna", reviewer_model: "gpt-6-sol" },
            {
                key: "size",
                status: "completed",
                outcome: "major",
                duration_ms: 2_100,
                tokens: 1_500,
                probabilities: { major: 0.88, minor: 0.12 },
            },
            { key: "review", status: "completed", outcome: "passed", duration_ms: minutes(34), tokens: 452_000, implementer_model: "gpt-6-luna", reviewer_model: "gpt-6-sol" },
            { key: "browser", status: "completed", outcome: "passed", duration_ms: minutes(3), tokens: null },
            { key: "merge", status: "completed", outcome: "passed", duration_ms: minutes(7), tokens: null },
            { key: "deploy", status: "completed", outcome: "passed", duration_ms: 95_000, tokens: null },
            { key: "verify", status: "failed", outcome: "failed", duration_ms: 38_000, tokens: null },
            { key: "rollback", status: "completed", outcome: "passed", duration_ms: 21_000, tokens: null },
        ],
    },
    {
        id: 377,
        template: "orbit-website/maintenance",
        title: "Weekly maintenance · 14 Sep",
        status: "completed",
        started_at: "2026-09-14T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "skipped", duration_ms: minutes(4), tokens: 38_000, implementer_model: "gpt-5.6-luna", reviewer_model: "gpt-6-sol" },
            { key: "size", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "review", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "browser", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "merge", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "deploy", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "verify", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "rollback", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
        ],
    },
];
