import type { TaskTemplate, TemplateRun } from "../flows/model";

/** Hand-written templates and runs for the flow viewer, until the Gateway serves them. */
export const templates: TaskTemplate[] = [
    {
        name: "maintenance",
        title: "Weekly maintenance",
        project: "Orbit Website",
        project_code: "WEB",
        status: "todo",
        cron: "0 3 * * 1",
        app: "orbit-website",
        tasks: [
            {
                key: "update",
                title: "Update dependencies",
                kind: "agent",
                brief: "Update the Composer and npm dependencies, and fix what the update breaks.",
                stats: {
                    runs: 12,
                    outcomes: { passed: 9, skipped: 3 },
                    avg_duration_ms: 14 * 60_000,
                    avg_tokens: 182_000,
                },
            },
            {
                key: "size",
                title: "Major upgrade?",
                kind: "decide",
                question: "Does this update contain a major version upgrade?",
                options: ["major", "minor"],
                evidence: ["update"],
                min_probability: 0.8,
                routes: { major: "review", minor: "browser" },
                stats: {
                    runs: 9,
                    outcomes: { major: 2, minor: 7 },
                    avg_duration_ms: 2_000,
                    avg_tokens: 1_400,
                },
            },
            {
                key: "review",
                title: "Adapt to major upgrades",
                kind: "agent",
                brief: "Read the changelogs of the major upgrades and adapt the App.",
                stats: {
                    runs: 2,
                    outcomes: { passed: 2 },
                    avg_duration_ms: 31 * 60_000,
                    avg_tokens: 420_000,
                },
            },
            {
                key: "browser",
                title: "Browser tests",
                kind: "check",
                commands: ["bunx playwright test --project=e2e"],
                stats: {
                    runs: 9,
                    outcomes: { passed: 8, failed: 1 },
                    avg_duration_ms: 3 * 60_000,
                    avg_tokens: null,
                },
            },
            {
                key: "merge",
                title: "Merge the pull request",
                kind: "merge",
                stats: {
                    runs: 8,
                    outcomes: { passed: 8 },
                    avg_duration_ms: 6 * 60_000,
                    avg_tokens: null,
                },
            },
            {
                key: "deploy",
                title: "Deploy production",
                kind: "action",
                operation: "instance:deploy",
                arguments: { instance: 4 },
                stats: {
                    runs: 8,
                    outcomes: { passed: 8 },
                    avg_duration_ms: 90_000,
                    avg_tokens: null,
                },
            },
            {
                key: "verify",
                title: "Smoke test production",
                kind: "check",
                commands: ["bunx playwright test --project=smoke --base-url=https://orbit.nckrtl.com"],
                routes: { passed: "complete", failed: "rollback" },
                stats: {
                    runs: 8,
                    outcomes: { passed: 7, failed: 1 },
                    avg_duration_ms: 40_000,
                    avg_tokens: null,
                },
            },
            {
                key: "rollback",
                title: "Roll back production",
                kind: "action",
                operation: "instance:rollback",
                arguments: { instance: 4 },
                routes: { passed: "fail" },
                stats: {
                    runs: 1,
                    outcomes: { passed: 1 },
                    avg_duration_ms: 20_000,
                    avg_tokens: null,
                },
            },
        ],
    },
    {
        name: "feature",
        title: "Feature",
        project: "Orbit",
        project_code: "ORB",
        status: "backlog",
        cron: null,
        app: null,
        tasks: [
            {
                key: "docs",
                title: "ADRs and documentation",
                kind: "agent",
                brief: "Write the ADR and update the documentation that the feature changes.",
            },
            {
                key: "implement",
                title: "Implementation",
                kind: "agent",
                brief: "Build the behavior the documentation describes.",
            },
            { key: "merge", title: "Merge the pull request", kind: "merge" },
        ],
    },
    {
        name: "content",
        title: "Website article",
        project: "Orbit Website",
        project_code: "WEB",
        status: "backlog",
        cron: null,
        app: "orbit-website",
        tasks: [
            {
                key: "draft",
                title: "Draft the article",
                kind: "agent",
                brief: "Write the article in the website repository from the brief.",
            },
            {
                key: "lint",
                title: "Prose and link checks",
                kind: "check",
                commands: ["bun run content:lint"],
            },
            { key: "merge", title: "Merge the pull request", kind: "merge" },
            {
                key: "deploy",
                title: "Deploy production",
                kind: "action",
                operation: "instance:deploy",
                arguments: { instance: 4 },
            },
        ],
    },
];

const minutes = (count: number) => count * 60_000;

export const runs: TemplateRun[] = [
    {
        id: 412,
        template: "maintenance",
        title: "Weekly maintenance · 28 Sep",
        status: "running",
        started_at: "2026-09-28T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "passed", duration_ms: minutes(12), tokens: 164_000 },
            {
                key: "size",
                status: "completed",
                outcome: "minor",
                duration_ms: 1_800,
                tokens: 1_300,
                probabilities: { minor: 0.94, major: 0.06 },
            },
            { key: "review", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "browser", status: "running", outcome: null, duration_ms: null, tokens: null },
            { key: "merge", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "deploy", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "verify", status: "todo", outcome: null, duration_ms: null, tokens: null },
            { key: "rollback", status: "todo", outcome: null, duration_ms: null, tokens: null },
        ],
    },
    {
        id: 398,
        template: "maintenance",
        title: "Weekly maintenance · 21 Sep",
        status: "failed",
        started_at: "2026-09-21T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "passed", duration_ms: minutes(16), tokens: 201_000 },
            {
                key: "size",
                status: "completed",
                outcome: "major",
                duration_ms: 2_100,
                tokens: 1_500,
                probabilities: { major: 0.88, minor: 0.12 },
            },
            { key: "review", status: "completed", outcome: "passed", duration_ms: minutes(34), tokens: 452_000 },
            { key: "browser", status: "completed", outcome: "passed", duration_ms: minutes(3), tokens: null },
            { key: "merge", status: "completed", outcome: "passed", duration_ms: minutes(7), tokens: null },
            { key: "deploy", status: "completed", outcome: "passed", duration_ms: 95_000, tokens: null },
            { key: "verify", status: "failed", outcome: "failed", duration_ms: 38_000, tokens: null },
            { key: "rollback", status: "completed", outcome: "passed", duration_ms: 21_000, tokens: null },
        ],
    },
    {
        id: 377,
        template: "maintenance",
        title: "Weekly maintenance · 14 Sep",
        status: "completed",
        started_at: "2026-09-14T03:00:00Z",
        tasks: [
            { key: "update", status: "completed", outcome: "skipped", duration_ms: minutes(4), tokens: 38_000 },
            { key: "size", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "review", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "browser", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "merge", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "deploy", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "verify", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
            { key: "rollback", status: "cancelled", outcome: null, duration_ms: null, tokens: null },
        ],
    },
];
