<?php

declare(strict_types=1);

use App\Domain\AppInstances\Dependencies\NpmVersionRange;

describe('npm version range', function (): void {
    it('matches node-semver loose validRange and satisfies', function (): void {
        // Generated by Fixtures/Dependencies/NodeSemver/generate.js with node-semver 7.8.5, the library npm uses.
        $vectors = json_decode((string) file_get_contents(dirname(__DIR__, 4).'/Fixtures/Dependencies/NodeSemver/vectors.json'), true, flags: JSON_THROW_ON_ERROR);
        $mismatches = [];

        foreach ($vectors as [$version, $spec, $valid, $satisfies]) {
            $range = NpmVersionRange::parse($spec);

            if (($range !== null) !== $valid || ($range?->satisfies($version) ?? false) !== $satisfies) {
                $mismatches[] = "{$version} {$spec}";
            }
        }

        expect(count($vectors))->toBeGreaterThan(2000);
        expect($mismatches)->toBe([]);
    });

    it('treats a dist-tag as no range', function (string $tag): void {
        expect(NpmVersionRange::parse($tag))->toBeNull();
    })->with(['latest', 'next', 'beta']);
});
